# Generated by Django 4.0.4 on 2022-04-18 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('type_user', models.CharField(choices=[('D', 'Donor'), ('R', 'Receiver'), ('S', 'Store'), ('H', 'Helper')], max_length=20)),
                ('donation_options', models.JSONField()),
                ('qr_code', models.CharField(max_length=500)),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
