# Generated by Django 4.0.4 on 2022-04-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
