# Generated by Django 4.0.4 on 2022-04-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_status_bio_recipient_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='bio',
            field=models.TextField(max_length=500),
        ),
    ]
