# Generated by Django 4.0.4 on 2022-04-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_created_ad_status_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='donation_options',
        ),
        migrations.AddField(
            model_name='status',
            name='donation_option_1',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='donation_option_2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='donation_option_3',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
            preserve_default=False,
        ),
    ]
