# Generated by Django 4.0.4 on 2022-04-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_status_donation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='type_user',
            field=models.CharField(choices=[('Donor', 'Donor'), ('Receiver', 'Receiver'), ('Store', 'Store'), ('Helper', 'Helper')], max_length=20),
        ),
    ]
