# Generated by Django 4.0.4 on 2022-04-18 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_status_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='donation_option_1',
        ),
        migrations.RemoveField(
            model_name='status',
            name='donation_option_2',
        ),
        migrations.RemoveField(
            model_name='status',
            name='donation_option_3',
        ),
        migrations.RemoveField(
            model_name='status',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='status',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='status',
            name='verified',
        ),
        migrations.AlterField(
            model_name='status',
            name='type_user',
            field=models.CharField(choices=[('Donor', 'Donor'), ('Recipient', 'Recipient'), ('Store', 'Store'), ('Helper', 'Helper')], max_length=20),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=500)),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('recipients', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.recipient')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_option_1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('donation_option_2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('donation_option_3', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.status')),
            ],
        ),
    ]
