# Generated by Django 4.0.4 on 2022-04-18 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_status_donation_option_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.status'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.status'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.status'),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.status'),
        ),
    ]
