# Generated by Django 4.0.4 on 2022-04-19 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0009_remove_recipient_status_recipient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='status',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='store',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='store',
            name='status',
        ),
        migrations.AddField(
            model_name='helper',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
