# Generated by Django 4.0.4 on 2022-04-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='accounts',
            field=models.ManyToManyField(to='main_app.account'),
        ),
    ]
