# Generated by Django 4.0.4 on 2022-04-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_transaction_donor_transaction_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='bio',
            field=models.CharField(default='This is a sample bio', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
